---

- name: Copying nginx repo
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo owner=root group=root
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Updating
  yum: name=* state=latest update_cache=yes
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Installing NginX packages
  yum:
    name: ['nginx.x86_64', 'nginx-module-geoip.x86_64']
    state: latest
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Creating security copy of /etc/nginx
  command: mv /etc/nginx /etc/nginx_original
  args:
    warn: false
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Copying nginx.tar.gz to server
  unarchive:
    src: nginx.tar.gz
    dest: /etc/
    owner: root
    group: root
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Creating NginX directories
  file: path={{item}} state=directory mode=0755 owner=nginx group=nginx
  with_items:
    - /var/www
    - /var/www/html
  notify: Restarting nginx
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

...
