---

# Instalacao de pacotes

- name: Installing packages
  apt: name={{mariadb_packages}} state=latest update_cache=yes install_recommends=yes
  vars:
    mariadb_packages:
      - mariadb-client
      - mariadb-server
      - python-mysqldb
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Creating root password
  command: openssl rand -base64 14 creates=/root/.my.cnf
  register: mysql_root_pass
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Display password
  debug:
    msg: "Password: {{ mysql_root_pass.stdout }}"
  when:
    - mysql_root_pass.changed
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Changing root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_pass.stdout }}
  with_items:
    - 127.0.0.1
    - localhost
  when:
    - mysql_root_pass.changed
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copying template .my.cnf
  template: src=.my.cnf dest=/root/.my.cnf owner=root group=root mode=0600
  when:
    - mysql_root_pass.changed
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Removing annonymous access
  mysql_user: name="" host=localhost state=absent
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Removing test database
  mysql_db: name=test state=absent
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Creating wordpress database
  mysql_db:
    name: 'wordpress'
    state: present
    login_user: 'root'
    login_password: "{{ mysql_root_pass.stdout }}"
    login_host: localhost
  when:
    - mysql_root_pass.changed
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Creating wordpress user and granting access
  mysql_user:
    name: 'wordpress'
    password: 'wordpress'
    priv: 'wordpress.*:ALL'
    host: '192.168.123.%'
    login_user: 'root'
    login_password: "{{ mysql_root_pass.stdout }}"
    login_host: localhost
  when:
    - mysql_root_pass.changed
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Granting remote access to MySQL
  lineinfile:
    dest=/etc/mysql/mariadb.conf.d/50-server.cnf
    regexp='bind-address            = 127.0.0.1'
    line='bind-address            = 192.168.123.30'
    state=present
  notify: Restarting MariaDB
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

...
